<?php

return [
    "http://localhost" => [
        "employees_schedule"            => false,
        "timeline_schedule"             => true,
        "due_payment"                   => true,
        "sessions_count"                => false,
        "national_id"                   => false,
        "email"                         => false,
        "vat"                           => false,
        'profile_attendance'            => true,
        'profile_attendance_dashboard'  => true,
        'sales_by'                      => false,
        'show_schedule_dashboard'       => false,
        'member_code_enabled'           => false,
        'is_reviewed_invoices'          => false,
        'trainer_services_option'       => false,
        'sports_option'                 => false,
        'minor'                         => false,
        'short_reports'                 => false,
        'add_to_class_in_invoice'       => false,
        'settlement_invoices'           => false
    ],
    "https://cougars.thebrandmakerz.com" => [
        "employees_schedule"            => false,
        "timeline_schedule"             => true,
        "due_payment"                   => true,
        "sessions_count"                => false,
        "national_id"                   => false,
        "email"                         => false,
        "vat"                           => false,
        'profile_attendance'            => true,
        'profile_attendance_dashboard'  => true,
        'sales_by'                      => false,
        'show_schedule_dashboard'       => false,
        'member_code_enabled'           => false,
        'is_reviewed_invoices'          => false,
        'trainer_services_option'       => false,
        'sports_option'                 => false,
        'minor'                         => false,
        'short_reports'                 => false,
        'add_to_class_in_invoice'       => false,
        'settlement_invoices'           => false
    ],
    "http://localhost/gymapp/public" => [
        "employees_schedule"            => true,
        "timeline_schedule"             => true,
        "due_payment"                   => true,
        "sessions_count"                => true,
        "national_id"                   => false,
        "email"                         => false,
        "vat"                           => false,
        'profile_attendance'            => true,
        'profile_attendance_dashboard'  => true,
        'sales_by'                      => false,
        'show_schedule_dashboard'       => false,
        'member_code_enabled'           => false,
        'is_reviewed_invoices'          => false,
        'trainer_services_option'       => false,
        'sports_option'                 => false,
        'minor'                         => true,
        'short_reports'                 => false,
        'add_to_class_in_invoice'       => true,
    ],
    "http://127.0.0.1:8000" => [
        "employees_schedule"            => true,
        "timeline_schedule"             => true,
        "due_payment"                   => true,
        "sessions_count"                => true,
        "national_id"                   => false,
        "email"                         => false,
        "vat"                           => false,
        'profile_attendance'            => false,
        'profile_attendance_dashboard'  => false,
        'sales_by'                      => false,
        'show_schedule_dashboard'       => false,
        'member_code_enabled'           => false,
        'is_reviewed_invoices'          => false,
        'trainer_services_option'       => false,
        'sports_option'                 => true,
        'minor'                         => true,
        'short_reports'                 => false,
        'add_to_class_in_invoice'       => true,
        'transactions_date'             => true
    ], // For mini

];
